/// ...
public extension Scuttlebutt.Network {
    
    /// ...
    typealias Address = String
    
    /// ...
    typealias Host = String

    /// ...
    typealias Port = UInt16

    /// ...
    typealias Endpoint = (host: Host, port: Port)

    /// ...
    typealias ResolvedEndpoint = (address: Address, port: Port)

}
